### ISSUE TITLE
Repeatable fields order ASC or DESC  !? 

### ISSUE THREAD

**Issue by blajanadrian** [bainternet/Tax-Meta-Class#100]
Hello bainternet ...

I have to fix a problem. For example:

Input:
1 - first value
2 - second value 
......

the code is:

<?php
$prefix = 'crI_';

$fields = array(
    array(
        'label' => '',
        'desc'  => '',
        'id'    => $prefix.'postimages',
        'type'  => 'repeatable',
        'sanitizer' => array(
            'featured' => 'meta_box_santitize_boolean',
            'title' => 'sanitize_text_field',
            'desc' => 'wp_kses_data'
        ),
        'repeatable_fields' => array (

                'url_images' => array(
                'label' => 'URL images',
                'id' => 'ui_images',
                'type' => 'text'
            )
        )
    )
);

$images_details = new custom_add_meta_box( 'crI_imagini', 'Imagini', $fields, 'post', true );

I would like that the values appears from the second value to first value  ...

Output: 
2 - second value 
1 - first value

reverse from input .... 

Code from output is:

<?php
                           $images_gallery = get_post_meta($post->ID, 'crI_postimages', true);
                           if ($images_gallery) {
                             foreach($images_gallery as $image_gallery) {
                           $images_det_gallery[] = "
                             etc etc ....
                           ";
                           }
                           $image_det_gallery = join( " ", $images_det_gallery );
                           }
                           ?>

                           <?php echo $image_det_gallery ?>

Thanks !

**Comment by bainternet** [comment]
cant make any sense of this.
