### ISSUE TITLE
Adding custom columns

### ISSUE THREAD

**Issue by lionel-bijaoui** [bainternet/Tax-Meta-Class#106]
Hi,

I found your plugin very good and it allow a lot of flexibility.
I have a request, maybe it is too hard or impossible to do, but it is worth the try.

Can you add an option to display a field in a custom columns in the admin table ?
It is possible to do it manually on a post type (ex. http://justintadlock.com/archives/2011/06/27/custom-columns-for-custom-post-types).
But is it possible to do it in a taxonomy page to show the meta information created with your plugin ?

It could be really useful to check if a taxonomy term have a picture set or not for example.

Anyway, thank you for your time.

Edit: found another source of info: http://wordpress.stackexchange.com/questions/28467/custom-columns-on-edit-tags-php-main-page
It seem like it is possible to do.

**Comment by bainternet** [comment]
Its not really something that should go in this class but you can do that very easily with `manage_edit-{TAXONOMY}_columns` filter to add the column and `manage_{TAXONOMY}_custom_column` to render that column.


ex:

```php
// Add the new column
add_filter("manage_edit-TAXONOMY_NAME_columns", function($columns){
	//add column key => label
	$columns['thumb'] = __('Thumb');
	return $columns;
});

//render the new column
add_filter("manage_TAXONOMY_NAME_custom_column", function($deprecated, $column_name, $term_id){
	if ('thumb' == $column_name) {
		$saved = get_term_meta($term_id, 'YOUR_IMAGE_FIELD_ID', true);
		if (isset($saved['url'])){
			echo '<img width="80" height="80" src="'.$saved['url'].'">';
		}else{
			echo 'NO IMAGE';
		}
	}
}, 10, 3);
```

**Comment by lionel-bijaoui** [comment]
OK, thank you for your detailed answer.

**Comment by mrtieutien** [comment]
Hi, 
Not working with WordPress 4.7.
