### ISSUE TITLE
How can i load css & js using theme function?

### ISSUE THREAD

**Issue by sajibtalukder** [bainternet/Tax-Meta-Class#108]
i wan to use this plugin from theme function (including in theme) . everything is ok. but css & js doesn't load . how can i fix that? please leave a suggestion.

advanced Thanks

**Comment by noesteijver** [comment]
In the file 'Tax-meta-class.php' on line 114 you'll find the path of the folder/files from the Tax-Meta-Class. Depending upon the place where you've put the folder, you should change the path.

**Comment by bainternet** [comment]
How can people still ask this?

set `use_with_theme` to the path of Tax-meta-class folder ex:
```php
<?php
$config = array(
  'id' => 'demo_meta_box',
  'title' => 'Demo Meta Box', 
  'pages' => array('category'), 
  'context' => 'normal', 
  'fields' => array(),
  'local_images' => false, 
  'use_with_theme' => get_template_directory_uri() . "/library/Tax-meta-class/" //or any other path to the Tax-meta-class folder
);
```
