### ISSUE TITLE
Using FontAwesome in select options

### ISSUE THREAD

**Issue by noesteijver** [bainternet/Tax-Meta-Class#109]
Hello,

I was wondering if there's a nice way to use FontAwesome icons in select options?

I've tried the following things:
- as html <i class="fa fa-money"></i> (FontAwesome is loaded in the head)
- as unicode &f0d6; (font-family of the select is set to FontAwesome)

But the two solutions above don't seem to work.

Anybody here found a way to do this? Many thanks!

**Comment by snakelabs** [comment]
You can insert a class for single option

Example
```
<select>
	<option class="fa fa-plus">Plus icon</option>
	<option class="fa fa-envelope">Envelope icon</option>
...
</select>
```
other this, you need to insert this css on your page

```
option.fa{ display:block !important; }
option.fa:before{ margin-right:5px !important; }
```

**Comment by snakelabs** [comment]
you need to insert icon code in hexadecimal format

Example
```
<option >&#xf0e0; Envelope Icon</option>
```
where f0e0 is unicode of icon http://fortawesome.github.io/Font-Awesome/icon/envelope/
