### ISSUE TITLE
Use get_stylesheet_directory_uri instead of get_template_directory_uri

### ISSUE THREAD

**Issue by jpSimkins** [bainternet/Tax-Meta-Class#110]
For `use_with_theme`, if you use `get_stylesheet_directory_uri` instead of `get_template_directory_uri` you can ensure that the correct theme is used. Otherwise, for child themes (as everyone should be using), this looks in the parent. I would also suggest an `inc` folder be default as to keep the files organized and not in the theme root. Otherwise, great job!

**Comment by bainternet** [comment]
Actually the class was first used in a parent theme which made more sense to me then and now.

that is way I left the `use_with_theme` parameter as a dynamic field and not fixed so in case you use it in a child theme or a plugin you can set the path yourself.
