### ISSUE TITLE
WYSIWYG field sometimes becomes empty in backend

### ISSUE THREAD

**Issue by killexx** [bainternet/Tax-Meta-Class#112]
Sometimes WYSIWYG field in Custom Taxonomy becomes empty in backend (on Taxonomy Edit Page), though in frontend it still has content written to it during last Save action.

(Wordpress 4.3.1)

**Comment by bainternet** [comment]
sometimes?

**Comment by killexx** [comment]
Sorry, there were errors on server during save process. I close this issue.
