### ISSUE TITLE
Color field not working

### ISSUE THREAD

**Issue by jorenvh** [bainternet/Tax-Meta-Class#113]
Hi,

I just installed your class. Great class by the way. But when I add a color field It won't work.

More specific the field is visible, the button to select a column is there but nothing happens when I click the button.

Cheers,
Joren

**Comment by crispouille** [comment]
Same for me, did you find something to fix it ?

**Comment by jorenvh** [comment]
I did't use the class, so I can't help you sorry.

**Comment by owkei** [comment]
Same here!
