### ISSUE TITLE
Getting taxonomy value.

### ISSUE THREAD

**Issue by webangon** [bainternet/Tax-Meta-Class#114]
First of all this a very basic question. But I did not get it done. 
I have text field id "text_field_id". I want to show this on category .So `$saved_data = get_tax_meta('3','text_field_id'); ` Here 3 is the category id. If I go "http://localhost/sofia/?cat=3"  this doesn't display anything. I have inspected database. Here is the screenshot
![untitled](https://cloud.githubusercontent.com/assets/7946657/12069359/3ac409c4-b055-11e5-9c43-36f8ed3abadc.png)

**Comment by killexx** [comment]
Bug on version 2.1.0
tested on Image field:

get_tax_meta($term->term_id, 'field_name');
returns empty string ('');

get_option( 'tax_meta_'.$term->term_id);
returns false

**Comment by hamid-kamalpour** [comment]
Dears,

I had same issue in **WP 4.4**, I found a solution after several time debugging it. You can use of **get_term_meta instead get_tax_meta**. the ***get_tax_meta*** **is new for wordpress 4.4** .

How do you can us it,
 
short, 
```php
get_term_meta($term_id,$element_field_id);
```
Find more information on following link,

https://developer.wordpress.org/reference/functions/get_term_meta/

Regards,

**Comment by bainternet** [comment]
In WordPress 4.4 and Up you can use the native *_term_meta functions:
get_term_meta
update_term_meta
delete_term_meta

instead of the *_tax_meta functions.

But if you still want to use the *_tax_meta functions then make sure to include `migration\tax_to_term_meta.php` before you include the tax meta class file.
