### ISSUE TITLE
get_tax_meta not working

### ISSUE THREAD

**Issue by vhinmanansala** [bainternet/Tax-Meta-Class#115]
Hi, great by plugin by the way and been using it for a while.

I'm having issue with get_tax_meta when using latest version of wordpress but it works when I try using it on older wordpress version. Am I the only one having issue with this?

**Comment by bainternet** [comment]
If you are using the latest version of WordPress then use `get_term_meta` instead of `get_tax_meta`

**Comment by BatenkovT** [comment]
Please, update/add this to your blog/readme. You made great Class! But I spent much time before found "get_term_meta"  here. Thx

**Comment by mrhammadasif** [comment]
Please, mention this thing somewhere. I wasted ~3 hours just to find this :-(
