### ISSUE TITLE
Image uploader not functioning

### ISSUE THREAD

**Issue by BenDarlington** [bainternet/Tax-Meta-Class#50]
Hello Ohad. 

I have an identical problem to NestedWeb viz: https://github.com/bainternet/Tax-Meta-Class/issues/34

Text fields function be the image upload button just doesn't do anything. 

My code is as follows. I have tried all the tips others have suggested to change the directory in tax-meta-class.php to no avail so I have reverted to the original class. 

Please find the below the code from my theme functions - do let me know what more I need to give you to help find the issue. 

Your help is hugely appreciated! Ben

require_once("Tax-meta-class/Tax-meta-class.php");

$config = array(
   'id' => 'charities_meta_box',  
   'title' => 'Charities Meta Box',  
   'pages' => array('charities'),  
   'context' => 'normal',  
   'fields' => array(),  
   'local_images' => false,  
  'use_with_theme' => get_template_directory_uri() . '/Tax-meta-class'  
);

$charities_custom_meta = new Tax_Meta_Class($config);

$charities_custom_meta->addText('charity_home_page',array('name'=> 'Charity Home Page'));
$charities_custom_meta->addText('charity_facebook_page',array('name'=> 'Charity Facebook Page URL'));
$charities_custom_meta->addImage('image_field_id',array('name'=> 'Charity Logo '));
$charities_custom_meta->addFile('file_field_id',array('name'=> 'My File '));

$charities_custom_meta->Finish();

**Comment by candyvdesigns** [comment]
This issue is still happening to me with the newest version of Wordpress. how frustrating!
