### ISSUE TITLE
get_tax_meta can't display Posts (as repeater or not) - multisite environment

### ISSUE THREAD

**Issue by leowski** [bainternet/Tax-Meta-Class#98]
Hi Ohad and guys,

Thanks for your great plugin. I works perfectly for me to set up and display all kind of fields except "posts".

I first tried as a repeater (cause that's what I wan't at the end) and then tried just like a simple post and still nothing appears.

The field does appear in the back-end but nothing in the front-end.

Here is what I got in my code : 
<code>$my_meta->addPosts($prefix.'produit_sidebar1',array('args' => array('post_type' => 'sidebar_bloc')),array('name'=> __('Sidebar bloc 1','tax-meta')));</code>

<code>$sidebar_bloc1 = get_tax_meta( $produit_cat->term_id, 'ba_produit_sidebar1', true);</code>

but there's nothing in it.

Is it cause I'm in a multisite environment?
Any idea?

Thanks a lot!

**Comment by StudioMomentum** [comment]
Hi @leowski, did you manage to display the repeater field. I am still having trouble display this also.

**Comment by leowski** [comment]
Yeah I did. Sorry for the delay but it was my bad. The plugin works great!
